#!/bin/bash
git add . # tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name tatusmatrix
git config --global user.email Tatjana.Solvojova@rtu.lv
git commit -m "Class_04"
git push origin main
